Rails.application.routes.draw do

  #devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see #http://guides.rubyonrails.org/routing.html
  #get 'floors/show'
  #get 'rooms/show'
  #post 'rooms/commented'
  #patch 'rooms/confirm'
  #get 'rooms/move'
  #get 'rooms/moved'
  #get 'rooms/edit'
  #patch 'rooms/update'
  #get '/rooms/noroom'
  #get '/rooms/reset'
  #get '/welcome/roomsearch'
  #get '/welcome/instruction'
  #post '/welcome/generate'
  #post 'rooms/alerted'
  get '/welcome/ezrt_privacy_policy'
  get '/welcome/ezkj'
  get '/welcome/ezkj_privacy_policy'
  get '/welcome/cbpb'
  get '/welcome/cbpb_privacy_policy'
  get '/welcome/ggpb'
  get '/welcome/ggpb_privacy_policy'
  get '/welcome/jbpb'
  get '/welcome/jbpb_privacy_policy'
  get '/welcome/bpbc'
  get '/welcome/bpbc_privacy_policy'
  get '/welcome/bpgr'
  get '/welcome/bpgr_privacy_policy'
  get '/welcome/asop'
  get '/welcome/asop_privacy_policy'
  get '/welcome/etpm'
  get '/welcome/etpm_privacy_policy'
  get '/welcome/mcpb'
  get '/welcome/mcpb_privacy_policy'
  get '/welcome/sgpb'
  get '/welcome/sgpb_privacy_policy'
  get '/welcome/pbct'
  get '/welcome/pbct_privacy_policy'
  get '/welcome/jbct'
  get '/welcome/jbct_privacy_policy'
  get '/welcome/hcpc'
  get '/welcome/hcpc_privacy_policy'
  get '/welcome/bbsd'
  get '/welcome/bbsd_privacy_policy'


  root to: 'welcome#index'
end

